import os
import requests
import base64
from datetime import datetime
from dotenv import load_dotenv
from auth_engine import get_dynamic_github_token

load_dotenv()


def create_draft_pr(blueprint_json, target_repo):
    print(f"🤖 Initializing Universal Patch Agent for {target_repo}...")

    # 1. Ask the Auth Engine for a fresh token for this specific repo
    try:
        dynamic_token = get_dynamic_github_token(target_repo)
    except Exception as e:
        return {
            "success": False,
            "message": f"❌ Token generation failed: {str(e)}",
        }

    # 2. Inject the token into the API headers (App Installation tokens use 'Bearer')
    headers = {
        "Authorization": f"Bearer {dynamic_token}",
        "Accept": "application/vnd.github.v3+json",
    }

    try:
        # 1. Locate default branch
        base_sha, base_branch = None, None
        for branch_name in ["main", "master"]:
            ref_url = f"https://api.github.com/repos/{target_repo}/git/refs/heads/{branch_name}"
            res = requests.get(ref_url, headers=headers)
            if res.status_code == 200:
                base_sha = res.json()["object"]["sha"]
                base_branch = branch_name
                break

        if not base_sha:
            return {"success": False, "message": "❌ Could not locate default branch."}

        # 2. Create isolation branch
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        new_branch = f"batcomputer-patch-{timestamp}"
        create_branch_url = f"https://api.github.com/repos/{target_repo}/git/refs"
        requests.post(
            create_branch_url,
            headers=headers,
            json={"ref": f"refs/heads/{new_branch}", "sha": base_sha},
        )
        print(f"🌿 Created isolation branch: {new_branch}")

        # 3. Apply Search-and-Replace to Actual Files
        solutions = blueprint_json.get("targeted_solutions", [])
        for sol in solutions:
            # Strip github prefix if AI included it
            file_path = sol.get("file_path", "").replace(f"github://{target_repo}/", "")
            search_block = sol.get("search_block", "")
            replace_block = sol.get("replace_block", "")

            # Fetch the live file content
            file_url = f"https://api.github.com/repos/{target_repo}/contents/{file_path}?ref={new_branch}"
            file_res = requests.get(file_url, headers=headers)

            if file_res.status_code == 200:
                file_data = file_res.json()
                file_sha = file_data["sha"]
                content = base64.b64decode(file_data["content"]).decode("utf-8")

                # Perform the surgical swap
                if search_block in content:
                    new_content = content.replace(search_block, replace_block)
                    encoded_content = base64.b64encode(
                        new_content.encode("utf-8")
                    ).decode("utf-8")

                    # Push the updated file to GitHub
                    requests.put(
                        file_url,
                        headers=headers,
                        json={
                            "message": f"Batcomputer Autonomous Fix: {sol.get('issue_resolved', 'Code Optimization')}",
                            "content": encoded_content,
                            "sha": file_sha,
                            "branch": new_branch,
                        },
                    )
                    print(f"✅ Safely patched {file_path}")
                else:
                    print(
                        f"⚠️ Search block not found exactly in {file_path}. Skipping safety patch."
                    )

        # 4. Extract the DevOps Advisory from the AI's blueprint
        advisory_note = blueprint_json.get("tech_debt_flags", {}).get(
            "architectural_note", "No additional architectural advisories provided."
        )

        # 5. Format the PR Body dynamically
        pr_body = (
            "This PR contains direct, tested code modifications generated by the Batcomputer QA engine.\n\n"
            "Review the file changes to approve the automated structural patches.\n\n"
            "---\n"
            "### 🛡️ DevOps Advisory\n"
            f"> {advisory_note}"
        )

        # 6. Open the Pull Request
        pr_url = f"https://api.github.com/repos/{target_repo}/pulls"
        pr_res = requests.post(
            pr_url,
            headers=headers,
            json={
                "title": f"🤖 Autonomous Batcomputer Code Review & Patches",
                "body": pr_body,
                "head": new_branch,
                "base": base_branch,
                "draft": True,
            },
        )

        if pr_res.status_code == 201:
            pr_data = pr_res.json()
            return {
                "success": True,
                "url": pr_data["html_url"],
                "message": "Successfully merged real file changes.",
            }
        else:
            return {"success": False, "message": "❌ Failed to open Pull Request."}

    except Exception as e:
        return {"success": False, "message": f"Critical Error: {str(e)}"}
